name: Test Action
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'test')
    name: test
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 #@v2

    - name: Checkout Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_URL="${{ github.event.issue.pull_request.url }}"
        PR_NUM=${PR_URL##*/}
        echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
        hub pr checkout $PR_NUM

    - name: Write file
      run: |
          echo "Hello world" > test.txt

    - name: Push changes
      run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Test commit"
          git push
