name: Test Action
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'test')
    name: test
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/github-script@v3
      id: get-pr
      with:
        script: |
          const request = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          }
          core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
          try {
            const result = await github.pulls.get(request)
            return result.data
          } catch (err) {
            core.setFailed(`Request failed with error ${err}`)
          }
    - uses: actions/checkout@v2
     # with:
     #   repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
     #   ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} # or .head.ref for branch name


    - name: Checkout Pull Request
      run: |
        hub pr checkout ${{ github.event.issue.number }}
        git remote -v
        git status

    - name: Write file
      run: |
          echo "Hello world" > test.txt

    - name: Push changes
      run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Test commit"
          git push
