name: Test Action
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'test')
    name: test
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@main

    - name: Checkout Pull Request
      run: |
        hub pr checkout ${{ github.event.issue.number }}
        git remote -v
        git status

    - name: Write file
      run: |
          echo "Hello world" > test.txt

    - name: Push changes
      run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Test commit"
          git push
